platform :ios, '14.0'
#use_modular_headers!
use_frameworks! :linkage => :static
 
# Ensure deterministic UUIDs are disabled if necessary
install! 'cocoapods',
         :deterministic_uuids => false


require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'




target 'RN1' do
  
  # Set up React Native dependencies
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false   # Set to true if you're using Hermes
    # :codegen_disabled => true
  )

  # Google Maps dependencies
  pod 'GoogleMaps', '~> 7.0.0' # Ensure you're using a compatible version
  pod 'Google-Maps-iOS-Utils'
   
   # Add Firebase dependencies
    pod 'Firebase/Messaging'
    pod 'Firebase/Core'
    pod 'FirebaseAnalytics' # Optional, for analytics
   
    pod 'GoogleUtilities', :modular_headers => true
 
    pod 'AFNetworking', '~> 4.0'

   
  
  
  
  
  # Define the permissions path at the base level
permissions_path = '../node_modules/react-native-permissions/ios'

  #pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  #pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  #pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"



   

#  target 'RN1Tests' do
#    inherit! :complete
#    # Pods for testing
#  end

  # Post-install script to exclude unsupported architectures for simulator builds
  post_install do |installer|
    #react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Exclude arm64 architecture for simulators on Apple Silicon Macs
        if config.name == 'Debug' || config.name == 'Release'
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
        end
      end
    end
  

    # Ensure Xcode 12.5 and later support
    react_native_post_install(installer)
  end
end
