name: Enable Status Check
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dummy Status Check
        run: echo "✅ Status Check Passed!"
